alias config='/usr/bin/git --git-dir=/Users/federicocecconi/.dotfiles/ --work-tree=/Users/federicocecconi'
alias config='/usr/bin/git --git-dir=/Users/federicocecconi/.dotfiles/ --work-tree=/Users/federicocecconi'
alias config='/usr/bin/git --git-dir=/Users/federicocecconi/.dotfiles/ --work-tree=/Users/federicocecconi'
alias config='/usr/bin/git --git-dir=/Users/federicocecconi/.dotfiles/ --work-tree=/Users/federicocecconi'
alias config='/usr/bin/git --git-dir=/Users/federicocecconi/.dotfiles/ --work-tree=/Users/federicocecconi'
